### ISSUE TITLE
Undefined offset 0  in UserAgentDetails Trait

### ISSUE THREAD

**Issue by petrosyan01** [jeremykenedy/laravel-logger#102] opened 2020-09-30 07:58 UTC
in file  vendor/jeremykenedy/laravel-logger/src/App/Http/Traits/UserAgentDetails.php:101
This issue going after writing log from incognito browser. in laravel_logger_activity table ,in column locale writing wrong value

**Comment by jeremykenedy** [comment] 2020-09-30 08:29
Duplicate of open issue.

**Closed by jeremykenedy** 2020-09-30 08:29 UTC
